### ISSUE TITLE
Host githistory.xyz not found

### ISSUE THREAD

**Issue by solsticedhiver** [pomber/git-history#110]
I don't know if it really qualifies as a bug but the domain `githistory.xyz` is nowhere to be found on many DNS servers.

```
$ host githistory.xyz 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases: 

Host githistory.xyz not found: 3(NXDOMAIN)
```

and so on

**Comment by fridzema** [comment]
Why do we even need to go trough a remote server?

**Comment by ffMathy** [comment]
Same problem here.

**Comment by tuzimoe** [comment]
Same problem here.

**Comment by pomber** [comment]
I hate DNS :rage:
I'm using netlify for the name server and namecheap is the domain registrar. 
Looks like namecheap is returning the right nameservers: https://whois.icann.org/en/lookup?name=githistory.xyz
> Name Server: DNS1.P05.NSONE.NET
Name Server: DNS2.P05.NSONE.NET
Name Server: DNS3.P05.NSONE.NET
Name Server: DNS4.P05.NSONE.NET

And I didn't change anything in netlify:
![image](https://user-images.githubusercontent.com/1911623/53422259-e8de5d80-39bd-11e9-9180-94c8ce4def57.png)
![image](https://user-images.githubusercontent.com/1911623/53422339-0c090d00-39be-11e9-92fb-3c2b8aa3c9ff.png)

Anyone who knows how this work can help?

**Comment by isaac-martin** [comment]
Netlify Support are super good. I would talk to them first.

**Comment by pomber** [comment]
> Netlify Support are super good. I would talk to them first.

Yes, I contacted them yesterday, they are usually fast

**Comment by pomber** [comment]
Ok, the domain is suspended because it's in a blacklist or something
  
https://gen.xyz/account/submitticket.php?action=unsuspend
![image](https://user-images.githubusercontent.com/1911623/53456331-c7589280-3a0c-11e9-893a-9d510e2ebbc8.png)

https://www.spamhaus.org/dbl/removal/record/githistory.xyz
![image](https://user-images.githubusercontent.com/1911623/53456356-e0f9da00-3a0c-11e9-8949-6364731d106d.png)

But spamhaus is declining the removal from the blacklist because of my email :confused: 
![image](https://user-images.githubusercontent.com/1911623/53456541-9e84cd00-3a0d-11e9-9341-a3c0bf1f553a.png)

**Comment by pomber** [comment]
Ok, I removed it from Spamhaus DBL 
![image](https://user-images.githubusercontent.com/1911623/53458695-e7408400-3a15-11e9-9a3b-2540009314a5.png)
And sent a unsuspend request to XYZ
![image](https://user-images.githubusercontent.com/1911623/53459227-ce38d280-3a17-11e9-94e9-3eb29c16a3a4.png)
:crossed_fingers:
